index:
    path: /
    defaults: { _controller: 'App\Controller\BoardController::index' }

photon:
    path: /photon
    defaults: { _controller: 'App\Controller\PhotonController::index' }

bitcoin-white:
    path: /bitcoin-white
    defaults: { _controller: 'App\Controller\BitcoinWhiteController::index' }
